### ISSUE TITLE
random setting for update-cron-daily-schedule config does not work

### ISSUE THREAD

**Issue by jneo8** [canonical/charm-logrotated#33]
The `random` setting for `update-cron-daily-schedule` does not work because the cron package running on Ubuntu (Vixie cron/ISC cron)[1] does not support this feature. The Ubuntu man page for cron [2] does not have anything on randomization of execution time either.

After checking the MP where the feature was introduced[3], it looks like this man page [4] was consulted to implement the random feature. But this feature is not implemented yet in the cron package for Ubuntu. So, some custom code needs to be written that would take START_HOUR,START_MIN,END_HOUR,END_MIN and output a random time in that range.

Therefore the implementation of the random feature needs to be fixed and this bug [5] has not been resolved yet. 

[1]: https://packages.ubuntu.com/jammy/cron
[2]: https://manpages.ubuntu.com/manpages/jammy/man5/crontab.5.html 
[3]: https://code.launchpad.net/~llama-charmers/charm-logrotated/+git/charm-logrotated/+merge/435334/comments/1155355
[4]: https://man7.org/linux/man-pages/man5/crontab.5.html
[5]: https://bugs.launchpad.net/charm-logrotated/+bug/1998895

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2023-05-17T17:02:40Z
 * owner: [dashmage](https://launchpad.net/~dashmage)
 * assignee: [dashmage](https://launchpad.net/~dashmage)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/2019990)

**Comment by Pjack** [comment]
https://code.launchpad.net/~dashmage/charm-logrotated/+git/charm-logrotated/+merge/443391
